src/Entity/Bar.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @UniqueEntity(fields="nom", message="Ce bar à déja été ajouté")
 * @Vich\Uploadable
 * @ORM\Entity(repositoryClass="App\Repository\BarRepository")
 */
class Bar
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $longitude;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="integer")
     */
    private $CodePostal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @Vich\UploadableField(mapping="images", fileNameProperty="photo")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bar")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BarLike", mappedBy="bar")
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="bar")
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Evenement", mappedBy="bar")
     */
    private $evenements;


    public function __construct()
    {
        $this->likes = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->evenements = new ArrayCollection();
    }

    public function setImageFile(File $photo = null)
    {
        $this->imageFile = $photo;
    }
    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->CodePostal;
    }

    public function setCodePostal(string $CodePostal): self
    {
        $this->CodePostal = $CodePostal;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getUsers(): ?User
    {
        return $this->users;
    }

    public function setUsers(?User $users): self
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return Collection|BarLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(BarLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setBar($this);
        }

        return $this;
    }

    public function removeLike(BarLike $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            // set the owning side to null (unless already changed)
            if ($like->getBar() === $this) {
                $like->setBar(null);
            }
        }

        return $this;
    }

    /**
     * @param User $user
     * @return bool
     */
    public function isLikedByUser(User $user): bool{
        foreach ($this->likes as $like){
            if($like->getUser()== $user) return true;
        }
        return false;

    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setBar($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getBar() === $this) {
                $commentaire->setBar(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setBar($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->contains($evenement)) {
            $this->evenements->removeElement($evenement);
            // set the owning side to null (unless already changed)
            if ($evenement->getBar() === $this) {
                $evenement->setBar(null);
            }
        }

        return $this;
    }


}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;


class SecurityController extends Controller
{


    /**
     * @Route("/login", name="login")
     */
    public function login(Request $request, AuthenticationUtils $authUtils)
    {
        // get the login error if there is one
        $error = $authUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authUtils->getLastUsername();

        return $this->render('security/connexion.html.twig', array(
            'last_username' => $lastUsername,
            'error' => $error,
        ));
    }

    /**
     * @Route("/registration", name="user_registration",methods={"GET","POST"})
     */
    public function registration(Request $request, ObjectManager $manager, UserPasswordEncoderInterface $encoder, AuthenticationUtils $authUtils)
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        $user->setRoles('ROLE_USER');
        if ($form->isSubmitted() && $form->isValid()) {
            $recaptcha = new \ReCaptcha\ReCaptcha('6Ldd4cEUAAAAADAGPTPXHdUszai86Z5pwpFuXtFM');
            $resp = $recaptcha->setExpectedHostname('127.0.0.1')
                ->verify($_POST['g-recaptcha-response']);
            if (isset($_POST['g-recaptcha-response'])) {
                if ($resp->isSuccess()) {
                    $hash = $encoder->encodePassword($user, $user->getPassword());
                    $user->setPassword($hash);
                    $manager->persist($user);
                    $manager->flush();
                    return $this->redirectToRoute('login');
                } else {

                    return $this->render('security/inscription.html.twig', [
                        'form' => $form->createView()
                    ]);
                }
            }
        }
        return $this->render('security/inscription.html.twig', [
            'form' => $form->createView()
        ]);
    }

}

templates/security/connexion.html.twig
{% extends "base.html.twig" %}
{% block title %} Connexion {% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('build/css/style.css') }}">
{% endblock %}
{% block body %}

    <link rel="stylesheet" href="{{ asset('build/css/form.css') }}">

    <div class="container">
        {% if error %}
            <div>
                <p>Erreur de saisi : {{ error.messageKey|trans(error.messageData, 'security') }}</p>
            </div>
            <br/>
        {% endif %}

        <p>Dernier identifiant saisi : {{ last_username }} </p>
        <br/>
        <form action="{{ path('login') }}" method="post">
            <h1>Connectez-vous</h1>
            <div class="form-group">
                <input type="text" onkeyup="checkUsername()" id="username" name="_username" value="{{ last_username }}" size="18" placeholder="Votre identifiant">
            </div>

            <div class="form-group">
                <input type="password" onkeyup="checkPass()" id="password" name="_password"  size="18" placeholder="Votre mot de passe">
            </div>
            <input type="hidden" name="_target_path" value="/" />
            <button type="submit" id="submit" disabled style="opacity: 0.5">VALIDER</button>
        </form>
    </div>
    
    <script>
        function checkUsername() {
            if (document.getElementById("username").value.length > 2){
                document.getElementById("username").style.border = "solid green 2px"
            }else {
                document.getElementById("username").style.border = "solid red 2px"
                document.getElementById("submit").style.opacity = "0.5"
                document.getElementById("submit").disabled = true
            }
            if (document.getElementById("username").value.length > 2 && document.getElementById("password").value.length > 2) {
                document.getElementById("submit").style.opacity = "1"
                document.getElementById("submit").disabled = false
            }
        }

        function checkPass() {
            if (document.getElementById("password").value.length > 2){
                document.getElementById("password").style.border = "solid green 2px"
            }else {
                document.getElementById("password").style.border = "solid red 2px"
                document.getElementById("submit").style.opacity = "0.5"
                document.getElementById("submit").disabled = true

            }
            if (document.getElementById("username").value.length > 2 && document.getElementById("password").value.length > 2) {
                document.getElementById("submit").style.opacity = "1"
                document.getElementById("submit").disabled = false
            }
        }
    </script>
{% endblock %}

templates/security/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SecurityController!{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('build/css/style.css') }}">
{% endblock %}

{% block body %}
    {% include "security/nav.html.twig" %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/ProjetTut/src/Controller/SecurityController.php'|file_link(0) }}">src/Controller/SecurityController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/ProjetTut/templates/security/index.html.twig'|file_link(0) }}">templates/security/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/security/inscription.html.twig
{% extends "base.html.twig" %}
{% block title %} Inscription {% endblock %}
{% import "security/recaptcha.html.twig" as formElements %}
{% block body %}

    <link rel="stylesheet" href="{{ asset('build/css/form.css') }}">

    <div class="container_insc">
        <div class="inscription">
            {{ form_start(form) }}
            <h1 class="inscr">Pour vous inscrire, renseignez les informations suivantes</h1>
            {{ form_row(form.username,{'label':'Nom d\'utilisateur - pseudo'}) }}
            {{ form_row(form.nom) }}
            {{ form_row(form.prenom,{'label':'Prénom'}) }}
            {{ form_row(form.dateNaissance) }}
            {{ form_row(form.email,{'label':'Adresse email'}) }}
            {{ form_row(form.password,{'label':'Mot de passe'}) }}
            {{ form_row(form.confirm_password,{'label':'Confirmation du mot de passe'}) }}
            {{ form_row(form.directeur) }}
            </br>
            {{ formElements.recaptcha("6Ldd4cEUAAAAADP8p17mGQ6UrhAD6ihgWRWwjETt") }}
            {{ form_row(form.submit, { 'label': 'VALIDER' }) }}
            {{form_end(form)}}
            </br>
        </div>

        <div class="lorem">
            <img src="logo_noir.png" />
        </div>
    </div>
{% endblock %}

templates/security/recaptcha.html.twig
{% macro recaptcha(siteKey)%}
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <div class="g-recaptcha" data-sitekey="{{siteKey}}"></div>
{% endmacro %}