src/Entity/Bar.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @UniqueEntity(fields="nom", message="Ce bar à déja été ajouté")
 * @Vich\Uploadable
 * @ORM\Entity(repositoryClass="App\Repository\BarRepository")
 */
class Bar
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $longitude;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="integer")
     */
    private $CodePostal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @Vich\UploadableField(mapping="images", fileNameProperty="photo")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bar")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BarLike", mappedBy="bar")
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="bar")
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Evenement", mappedBy="bar")
     */
    private $evenements;


    public function __construct()
    {
        $this->likes = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->evenements = new ArrayCollection();
    }

    public function setImageFile(File $photo = null)
    {
        $this->imageFile = $photo;
    }
    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->CodePostal;
    }

    public function setCodePostal(string $CodePostal): self
    {
        $this->CodePostal = $CodePostal;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getUsers(): ?User
    {
        return $this->users;
    }

    public function setUsers(?User $users): self
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return Collection|BarLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(BarLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setBar($this);
        }

        return $this;
    }

    public function removeLike(BarLike $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            // set the owning side to null (unless already changed)
            if ($like->getBar() === $this) {
                $like->setBar(null);
            }
        }

        return $this;
    }

    /**
     * @param User $user
     * @return bool
     */
    public function isLikedByUser(User $user): bool{
        foreach ($this->likes as $like){
            if($like->getUser()== $user) return true;
        }
        return false;

    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setBar($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getBar() === $this) {
                $commentaire->setBar(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setBar($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->contains($evenement)) {
            $this->evenements->removeElement($evenement);
            // set the owning side to null (unless already changed)
            if ($evenement->getBar() === $this) {
                $evenement->setBar(null);
            }
        }

        return $this;
    }


}

src/Form/BarType.php
<?php

namespace App\Form;

use App\Entity\Bar;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class BarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('Email')
            ->add('telephone')
            ->add('Ville')
            ->add('adresse')
            ->add('CodePostal')
            ->add('latitude')
            ->add('longitude')
            ->add('Description')
            ->add('imageFile', VichImageType::class,[
                'label' => 'Photo du bar',
                'required' => false
            ])
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Bar::class,
        ]);
    }
}

src/Controller/BarController.php
<?php

namespace App\Controller;

use App\Entity\Bar;
use App\Entity\BarLike;
use App\Entity\Commentaire;
use App\Entity\Notification;
use App\Form\BarType;
use App\Form\CommentaireType;
use App\Form\ModifBarType;
use App\Repository\BarLikeRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Twig\Environment;

class BarController extends AbstractController
{

    // ------------------- Partie Utilisateur -------------------------
    // ajouter un bar
    /**
     * @Route("/bar/add", name="bar.add")
     */
    public function ajouterBar(Request $request, Environment $twig, RegistryInterface $doctrine, FormFactoryInterface $formFactory){
        $form=$formFactory->createBuilder(BarType::class)->getForm();
        $form->handleRequest($request);
        $user=$this->getUser();
        if($form->isSubmitted() && $form->isValid()){
            $bar=$form->getData();
            $bar->setUsers($user);
            $doctrine->getEntityManager()->persist($bar);
            $doctrine->getEntityManager()->flush();

            return new Response($twig->render('accueil.html.twig'));
        }
        return $this->render('bar/formBar.html.twig', [
            'form' => $form->createView()
        ]);
    }
    // liste des bars
    /**
     * @Route("/showBar", name="bar.show")
     */
    public function showBar(Environment $twig, RegistryInterface $doctrine, Request $request){
        $bar=$doctrine->getRepository(Bar::class)->findAll();
        $commentaire = $doctrine->getRepository(Commentaire::class)->findAll();
        return new Response($twig->render('bar/showBar.html.twig', ['bar' => $bar, 'commentaire'=>$commentaire]));
    }

    /**
     * @Route("/bar/edit", name="bar.edit")
     */
    public function modifierBar(){

    }

    // liker ou disliker un bar

    /**
     * @Route("/showBar/like/{id}", name="bar.like")
     * @param ObjectManager $manager
     * @param Bar $bar
     * @param BarLikeRepository $barRepo
     * @return Response
     */
    public function like(ObjectManager $manager, Bar $bar, BarLikeRepository $barRepo): Response{
        $user= $this->getUser();
        if(!$user){
          //  return $this->json(['code'=> 403, 'message'=>'You have to be connected'],403);
            return $this->redirectToRoute('bar.show');
        }
        if ($bar->isLikedByUser($user)){
            $like = $barRepo->findOneBy(['bar'=>$bar, 'user'=>$user]);
            $manager->remove($like);
            $manager->flush();
            return $this->redirectToRoute('bar.show');
        }
        $like = new BarLike();
        $like->setUser($user);
        $like ->setBar($bar);
        $manager->persist($like);
        $manager->flush();
        return $this->redirectToRoute('bar.show');
    }



    // ------------------------ Partie commentaire -----------------------------------
    // Ajouter un commentaire
    /**
     * @Route("/showBar/commentaire", name="commentaire.add")
     */
    public function addCommentaire(Environment $twig, RegistryInterface $doctrine, Request $request){
     //   $donnees['contenue']=$request->get('contenue');
        $donnees['id']= $request->get('bar');
        $bar= $doctrine->getRepository(Bar::class)->findOneBy(['id'=>$request->get('bar')]);
        $user=$this->getUser();
        $commentaire = new Commentaire();
        $commentaire->setUser($user)
            ->setBar($bar)
            ->setContenue($request->get('contenue'));
        $doctrine->getEntityManager()->persist($commentaire);
        $doctrine->getEntityManager()->flush();
        return $this->redirectToRoute('bar.show');
    }

    // Supprimer un commentaire
    /**
     * @Route("/showBar/commentaire/del", name="commentaire.del")
     */
    public function deleteCommentaire(Request $request, Environment $twig, RegistryInterface $doctrine, FormFactoryInterface $formFactory)
    {
        $commentaire=$doctrine->getRepository(Commentaire::class)->find($request->query->get('id'));
        $doctrine->getEntityManager()->remove($commentaire);
        $doctrine->getEntityManager()->flush();
        return $this->redirectToRoute('bar.show');
    }






    // ------------------------------ Partie Admin -------------------------------------
    // affichage de la liste des bars
    /**
     * @Route("/admin/showBar", name="admin.showBar")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function showBarAdmin(RegistryInterface $doctrine,Environment $twig){
        $bar = $doctrine->getRepository(Bar::class)->findAll();
        return new Response($twig->render('admin/bar/showBar.html.twig', ['bar' => $bar]));
    }

    // supprimer un bar par l'admin
    /**
     * @Route("/admin/delete/bar", name="admin.deleteBar", methods={"DELETE"})
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function deleteUserAdmin(Request $request, Environment $twig, RegistryInterface $doctrine)
    {
        $bar=$doctrine->getRepository(Bar::class)->find($request->query->get('id'));
        $doctrine->getEntityManager()->remove($bar);
        $doctrine->getEntityManager()->flush();
        return $this->redirectToRoute('admin.showBar');
    }

    // ajouter un bar par l'admin
    /**
     * @Route("/admin/addBar", name="admin.addBar", methods={"POST"})
     */
    public function ajouterBarAdmin(Request $request, Environment $twig, RegistryInterface $doctrine){
        $bar = new Bar();
        $form=$this->createForm(BarType::class, $bar);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $bar=$form->getData();
            $doctrine->getEntityManager()->persist($bar);
            $doctrine->getEntityManager()->flush();

            return $this->redirectToRoute('admin.showBar');
        }
        return $this->render('admin/bar/inscrireBar.html.twig', [
            'form' => $form->createView()
        ]);
    }

    // modifier un bar
    /**
     * @Route("/admin/editBar", name="admin.editBar", methods={"PUT"})
     */
    public function editBarAdmin(Request $request, RegistryInterface $doctrine, FormFactoryInterface $formFactory,UserPasswordEncoderInterface $encoder)
    {
        $bar=$doctrine->getRepository(Bar::class)->find($request->query->get('id'));
        $form=$formFactory->createBuilder(ModifBarType::class,$bar,  array(
            'method' => 'PUT',
        ))->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $doctrine->getEntityManager()->flush();
            return $this->redirectToRoute('admin.showBar');
        }
        return $this->render('admin/bar/modifierBar.html.twig',['form'=>$form->createView()]);
    }
}

templates/bar/formBar.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <link rel="stylesheet" href="{{ asset('build/css/form.css') }}">

    <div class="inscr_bar">
        {{ form_start(form) }}
        <h1>Voulez - vous ajouter un <b>bar</b> à la liste ?</h1>
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
    <br/>

{% endblock %}

templates/bar/showBar.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    {#inserer js pour faire apparaître les div petit a petit#}
    <!--<script src="build/js/list_bar_fade.js"></script>-->
    <script src="build/js/javascript.js"></script>
    <!--<script src="build/js/div_fade.js"></script>-->

    <style>
        h1 {
            text-align: center;
            font-family: "Century Gothic";
            margin-top: 2%;
        }
        .blockbar {
            display: block;
            opacity: 1.0;
        }
    </style>
    <h1>Venez profitez des bars à Belfort</h1>
    <br/>

    {% for bars in bar  %}
        <div class="blockbar">
            <div class="try">
                <img style="width:250px;height:250px" src="{{asset('images/')}}{{bars.photo}}" alt="image de {{bars.photo}}" >
            </div>

            <div class="textDroiteBar">
                    <h2>{{ bars.nom }}</h2>
                    <br>
                   <a> <b>Adresse : </b><br>{{ bars.adresse }}</a>
                    <a>{{ bars.codePostal }}</a><a> {{ bars.ville }}</a>
                    <br>
                    <br>
                    <a><b>Numéro de téléphone :</b><br> {{ bars.telephone }}</a>
                    <br>
                    <br>
                    <a><b>Description :</b></a><br>
                    <a>{{ bars.description }}</a><br><br>
                    <a>Commentaire :</a><br>
                    {% for commentaires in commentaire %}
                        {% if commentaires.bar.id == bars.id %}
                            <div class="commentaire">
                                {% if app.user == commentaires.user %}
                                    <a href="{{ path('commentaire.del',{id: commentaires.id}) }}" class="close icon" style="margin-left: 29%"></a>
                                {% endif %}
                                <a>{{ commentaires.user.username }}: {{ commentaires.contenue }}</a>
                            </div>
                        {% endif %}
                    {% endfor %}

                <form action="{{ path('commentaire.add') }}" method="post" >
                    <input style="display: block; width: 400px;margin-top: 20px" type="text" name="contenue" placeholder="Laisser un commentaire"><br>
                    <input type="hidden" name="bar" value="{{ bars.id }}">
                    <input type="submit">
                </form><br><br>

                <a href="{{ path('bar.like', {id: bars.id}) }}" class="btn btn-link js-like" id="like" style="margin-left: 35% ">
                    {% if app.user and bars.isLikedByUser(app.user) %}
                        <i class="fas fa-thumbs-up"></i>
                    {% else %}
                        <i class="far fa-thumbs-up"></i>
                    {% endif %}
                    <span class="js-likes">{{ bars.likes | length  }}</span>
                    <span class="js-label">Like</span>
                </a>
            </div>
            <br/>
        </div>
        <br>
    {% endfor %}
    <br/>

{% endblock %}
{#Script pour like#}
{% block javascripts %}
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        const axios = require('axios');
        function onClickBtn(event){
            event.preventDefault();
            const url = this.href;
            const spn = this.querySelector('span.js-likes');
            axios.get(url).then(function (response) {
                spn.textContent = response.data.likes;
            });
        }

        document.querySelectorAll('a.js-like').forEach(function(link) {
            link.addEventListener('click', onclickBtn);
        })
    </script>
{% endblock %}