src/Entity/Amis.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AmisRepository")
 */
class Amis
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isAmis;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id1;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id2;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notification", mappedBy="demandeAmis")
     */
    private $notifications;

    public function __construct()
    {
        $this->notifications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsAmis(): ?bool
    {
        return $this->isAmis;
    }

    public function setIsAmis(?bool $isAmis): self
    {
        $this->isAmis = $isAmis;

        return $this;
    }

    public function getUserId1(): ?User
    {
        return $this->user_id1;
    }

    public function setUserId1(?User $user_id1): self
    {
        $this->user_id1 = $user_id1;

        return $this;
    }

    public function getUserId2(): ?User
    {
        return $this->user_id2;
    }

    public function setUserId2(?User $user_id2): self
    {
        $this->user_id2 = $user_id2;

        return $this;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications[] = $notification;
            $notification->setDemandeAmis($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->contains($notification)) {
            $this->notifications->removeElement($notification);
            // set the owning side to null (unless already changed)
            if ($notification->getDemandeAmis() === $this) {
                $notification->setDemandeAmis(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;


use App\Entity\User;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('password',PasswordType::class)
            ->add('confirm_password',PasswordType::class)
            ->add('email',EmailType::class)
            ->add('nom' )
            ->add('prenom')
            ->add('dateNaissance',DateType::class, [
                'widget' => 'choice',
            ])
            ->add('directeur',CheckboxType::class,  ['required' => false,'mapped' => true ])
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Amis;
use App\Entity\User;
use App\Form\UserType;
use Doctrine\Common\Persistence\ObjectManager;
use ReCaptcha\RequestMethod\Post;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Twig\Environment;
use App\Repository\UserRepository;

class UserController extends AbstractController
{

    // ----------------------- Partie Admin ------------------------
    // Affiche les utilisateurs
    /**
     * @Route("/admin/showUser", name="admin.showUser")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function showUserAdmin(RegistryInterface $doctrine,Environment $twig){
        $user=$doctrine->getRepository(User::class)->findByRole('ROLE_USER');
        return new Response($twig->render('admin/user/showUser.html.twig', ['user' => $user]));
    }

    // Supprime un utilisateur

    /**
     * @Route("/admin/delete/user", name="admin.deleteUser", methods={"DELETE"})
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function deleteUserAdmin(Request $request, Environment $twig, RegistryInterface $doctrine, FormFactoryInterface $formFactory)
    {
        $user=$doctrine->getRepository(User::class)->find($request->query->get('id'));
        $doctrine->getEntityManager()->remove($user);
        $doctrine->getEntityManager()->flush();
        return $this->redirectToRoute('admin.showUser');
    }

    //filtre des utilisateurs

    /**
     * @Route("/user/filtre", name="user.filtre")
     */
    public function filtreUser(RegistryInterface $doctrine,Environment $twig, Request $request){

        $user=$doctrine->getRepository(User::class)->filterUser($request->get("filtre"));
        $userC = $this->getUser();
        $amis = $doctrine->getRepository(Amis::class)->getAmis($userC);

        return new Response($twig->render('user/listeUser.html.twig', ['user' => $user, 'amis' => $amis]));
    }


    // modifier les données d'un utilisateur
    /**
     * @Route("/admin/editUser", name="admin.editUser", methods={"PUT"})
     */
    public function editUser(Request $request, RegistryInterface $doctrine, FormFactoryInterface $formFactory,UserPasswordEncoderInterface $encoder)
    {
        $user=$doctrine->getRepository(User::class)->find($request->query->get('id'));
        $form=$formFactory->createBuilder(UserType::class,$user,  array(
            //'action' => $this->generateUrl('target_route'),
            'method' => 'PUT',
        ))->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $hash = $encoder->encodePassword($user,$user->getPassword());
            $user->setPassword($hash);
            $doctrine->getEntityManager()->flush();
            return $this->redirectToRoute('admin.showUser');
        }
        return $this->render('admin/user/editUser.html.twig',['form'=>$form->createView()]);
    }

    // ajouter un utilisateur
    /**
     * @Route("/admin/inscriptionUser", name="admin.inscriptionUser", methods={"POST"})
     */
    public function registration(Request $request, ObjectManager $manager, UserPasswordEncoderInterface $encoder,AuthenticationUtils $authUtils, RegistryInterface $doctrine){
        $user = new User();
        $form= $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        $user->setRoles('ROLE_USER');
        if($form->isSubmitted() && $form->isValid()){
            $hash = $encoder->encodePassword($user,$user->getPassword());
            $user->setPassword($hash);
            $manager->persist($user);
            $manager->flush();
            return $this->redirectToRoute('admin.showUser');
        }
        return $this->render('admin/user/inscription.html.twig', [
            'form'=>$form->createView()
        ]);
    }




    // ------------------  Partie User ------------------------
    // Affiche les utilisateurs pour pouvoirs les ajouter en amis
    /**
     * @Route("/User/list", name="user.userList")
     */
    public function showUser(RegistryInterface $doctrine,Environment $twig){
        $user=$doctrine->getRepository(User::class)->findByRole('ROLE_USER');
        $userC = $this->getUser();
        $amis = $doctrine->getRepository(Amis::class)->getAmis($userC);
      
        return new Response($twig->render('user/listeUser.html.twig', ['user' => $user, 'amis' => $amis]));
    }


}

templates/user/_showAmis.html.twig
{# A inclure dans d'autres pages #}
<div id="notificationsContainer">
    <h3>Amis :</h3>
    {% for ami in amis %}
        {% if app.user == ami.userId1 and ami.isAmis == 1 %}
            <a href="{{ path('amis.tchat', {id: ami.userId2.id }) }}" class="boutonAmi">
                <div class="elementDeDroite divAmi">
                    <div class="avatarListeAmi">
                        <img src="{{asset('images/')}}{{ami.userId2.photo|default('default.png')}}" alt="image de {{ami.userId2.photo}}" >
                    </div>
                    <div class="pseudoListeAmi">
                        {{ ami.userId2.username }}<div class="messageListeAmi">
                            <img src="{{asset('images/message_icon.png')}}" alt="Chatter">
                        </div>
                    </div>
                </div>
            </a>
        {% endif %}
        {% if app.user == ami.userId2 and ami.isAmis == 1 %}
            <a href="{{ path('amis.tchat', {id: ami.userId1.id }) }}" class="boutonAmi">
                <div class="elementDeDroite divAmi">
                    <div class="avatarListeAmi">
                        <img src="{{asset('images/')}}{{ami.userId1.photo|default('default.png')}}" alt="image de {{ami.userId1.photo}}" >
                    </div>
                    <div class="pseudoListeAmi">
                        {{ ami.userId1.username }}<div class="messageListeAmi">
                            <img src="{{asset('images/message_icon.png')}}" alt="Chatter">
                        </div>
                    </div>
                </div>
            </a>
        {% endif %}
    {% endfor %}
</div>

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/ProjetTut/barathon1/src/Controller/UserController.php'|file_link(0) }}">src/Controller/UserController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/ProjetTut/barathon1/templates/user/index.html.twig'|file_link(0) }}">templates/user/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/user/listeUser.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <!-- -------------------------------------ajout amis cassée----------------------------------------- -->

{#    <div class="add_ami">#}
{#        <form method="post" action="#">#}
{#            <input type="hidden" name="_method" value="post" >#}
{#            <input type="submit" class="btn btn-outline-success" value="Ajouter utilisateur">#}
{#        </form>#}
{#    </div>#}


    <div class="container">
            <form method="get" action="{{ path('user.filtre') }}" style="margin-left: 50px;">
                <label>Recheche (username) :
                    <input type="text" name="filtre"></label>
                <input type="submit" style="float : none;" value="Filtrer">
            </form>


                <table class="table table-bordered">
                    <tbody>

                    {% set i=0 %}
                    {% for users in user %}

                        {% if  app.user != users %}
                            <td>
                                <div class="blockuser">
                                    <img style="width:200px;height:auto" src="{{asset('images/')}}{{users.photo|default('default.png')}}" alt="image de {{users.photo}}" >
                                    <br/>
                                    <br/>
                                    <h2 class="textuser">{{ users.username }}</h2>
                                    <div class="textuser" >
                                          <a> {{ users.nom }} {{ users.prenom }}</a>
                                    </div>
                                    <br/>
                                    {% set compteur =0 %}
                                    {% for ami in amis %}
                                        {% if users == ami.userId1 or users == ami.userId2  %}
                                            {% set compteur=1 %}
                                            {% if ami.isAmis == 1 %}
                                            <div class="formulaire">
                                                <a style="margin-left: 45px; color: #00e000"> Vous êtes amis</a>
                                            </div>
                                            {% else %}
                                                <div class="formulaire">
                                                    <a style="margin-left: 12px; color: #00e000"> En attende d'acceptation</a>
                                                </div>

                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                    {% if compteur == 0 %}
                                        <div class="formulaire">
                                            <form method="post" action="{{ path('user.addAmis',{id: users.id}) }}">
                                                <input type="submit" class="btn btn-outline-success" value="Ajouter un ami ">
                                            </form>
                                        </div>
                                    {% endif %}
                                </div>
                                {% set i=i+1 %}
                                {% if i%5 == 0 %}
                                    <tr>
                                {% endif %}
                            </td>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
                <br/>
    </div>
{% endblock %}